name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch: # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Manshi-Singh547075
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
          theme: github-dark

      - name: Push SVG to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist

